version: "3.7"
services:
  web:
    build: ./docker/web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links: 
      - db
    volumes: 
      - ${DOCUMENT_ROOT-./}:/var/www/html
  db:
    build: ./docker/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: <mysql root pw>
      MYSQL_USER: <mysql user>
      MYSQL_PASSWORD: <mysql pw>
    ports:
      - "3306:3306"
  